server:
  port: 8085

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
        - id: ms-tela-service
          uri: lb://ms-tela-service
          predicates:
            - Path=/tela/**
          filters:
            - AuthFilter
        - id: ms-pedido-service
          uri: lb://ms-pedido-service
          predicates:
            - Path=/exportacion/**
          filters:
            - AuthFilter



